# Generated by Django 4.2.13 on 2024-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('cake_id', models.AutoField(db_column='cake_ID', primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('cost', models.TextField()),
                ('layers_count', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cake',
            },
        ),
        migrations.CreateModel(
            name='CakeAddition',
            fields=[
                ('cake_addition_id', models.AutoField(db_column='cake_addition_ID', primary_key=True, serialize=False)),
                ('ingridient', models.TextField(unique=True)),
                ('cost_per_gram', models.IntegerField()),
                ('primary_color', models.TextField()),
                ('secondary_color', models.TextField()),
            ],
            options={
                'db_table': 'Cake_addition',
            },
        ),
        migrations.CreateModel(
            name='CakeCoverage',
            fields=[
                ('cake_coverage_id', models.AutoField(db_column='Cake_coverage_ID', primary_key=True, serialize=False)),
                ('ingridient', models.TextField(unique=True)),
                ('cost_per_gram', models.IntegerField()),
                ('density', models.IntegerField()),
                ('primary_color', models.TextField()),
                ('secondary_color', models.TextField()),
            ],
            options={
                'db_table': 'Cake_coverage',
            },
        ),
        migrations.CreateModel(
            name='CakeShape',
            fields=[
                ('cake_shape_id', models.AutoField(db_column='cake_shape_ID', primary_key=True, serialize=False)),
                ('shape', models.TextField(unique=True)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'Cake_shape',
            },
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('cake_size_id', models.AutoField(db_column='cake_size_ID', primary_key=True, serialize=False)),
                ('type', models.TextField(unique=True)),
                ('base_area', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Cake_size',
            },
        ),
        migrations.CreateModel(
            name='CakeTopping',
            fields=[
                ('cake_topping_id', models.AutoField(db_column='Cake_topping_ID', primary_key=True, serialize=False)),
                ('ingridient', models.TextField(unique=True)),
                ('cost_per_gram', models.IntegerField()),
                ('density', models.IntegerField()),
                ('primary_color', models.TextField()),
                ('secondary_color', models.TextField()),
            ],
            options={
                'db_table': 'Cake_topping',
            },
        ),
        migrations.CreateModel(
            name='LayerBase',
            fields=[
                ('layer_base_id', models.AutoField(db_column='layer_base_ID', primary_key=True, serialize=False)),
                ('ingridient', models.TextField(unique=True)),
                ('cost_per_gram', models.IntegerField()),
                ('density', models.IntegerField()),
                ('primary_color', models.TextField()),
                ('secondary_color', models.TextField()),
            ],
            options={
                'db_table': 'Layer_base',
            },
        ),
        migrations.CreateModel(
            name='LayerFilling',
            fields=[
                ('layer_filling_id', models.AutoField(db_column='layer_filling_ID', primary_key=True, serialize=False)),
                ('ingridient', models.TextField(unique=True)),
                ('cost_per_gram', models.IntegerField()),
                ('density', models.IntegerField()),
                ('primary_color', models.TextField()),
                ('secondary_color', models.TextField()),
            ],
            options={
                'db_table': 'Layer_filling',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='order_ID', primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('delivery_date', models.TextField()),
                ('price', models.FloatField()),
                ('delivery_address', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_ID', primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('last_name', models.TextField()),
                ('date_birth', models.TextField()),
                ('phone_number', models.TextField(unique=True)),
                ('is_superuser', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('order_content_id', models.AutoField(db_column='order_content_ID', primary_key=True, serialize=False)),
                ('cake', models.ForeignKey(db_column='cake_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.cake')),
                ('order', models.ForeignKey(db_column='order_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
            ],
            options={
                'db_table': 'Order_content',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.user'),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_id', models.AutoField(db_column='layer_ID', primary_key=True, serialize=False)),
                ('layer_base', models.ForeignKey(db_column='layer_base_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.layerbase')),
                ('layer_filling', models.ForeignKey(db_column='layer_filling_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.layerfilling')),
            ],
            options={
                'db_table': 'Layer',
            },
        ),
        migrations.CreateModel(
            name='CakeStructure',
            fields=[
                ('cake_structure_id', models.AutoField(db_column='cake_structure_ID', primary_key=True, serialize=False)),
                ('cake', models.ForeignKey(db_column='cake_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.cake')),
                ('layer', models.ForeignKey(db_column='layer_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.layer')),
            ],
            options={
                'db_table': 'Cake_structure',
            },
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_addition',
            field=models.ForeignKey(db_column='cake_addition_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.cakeaddition'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_coverage',
            field=models.ForeignKey(db_column='cake_coverage_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.cakecoverage'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_shape',
            field=models.ForeignKey(db_column='cake_shape_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.cakeshape'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_size',
            field=models.ForeignKey(db_column='cake_size_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.cakesize'),
        ),
        migrations.AddField(
            model_name='cake',
            name='cake_topping',
            field=models.ForeignKey(db_column='cake_topping_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.caketopping'),
        ),
    ]
